[package]
# Semantic Versioning is used: https://semver.org/
version = "1.2.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["StephenT0"]

# The title and description fields are primarily for displaying extension info in UI
title = "Isometric Camera"
description="Extension to spawn and simplify the use of an isometric camera."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Camera"

# Keywords for the extension
keywords = ["Camera", "Isometric,"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import funkyboy.isometric.camera".
[[python.module]]
name = "funkyboy.isometric.camera"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
